resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repo is located
      gitProvider: my_github
      # Repository path, including org name/repo name
      # path: jfbetapipeorg/Org_test_Automation_Webhooks
      path: Gyanar-git/myFirstRepo
      files: 
       include: ^README.md$
      branches:
        # Specifies which branches will trigger dependent steps
        include: ^{{gitBranch}}$
      buildOn:
        pullRequestCreate: true
        tagCreate: true
      cancelPendingRunsOn:
        pullRequestUpdate: true
pipelines:
  - name: my_first_pipeline
    steps:
      - name: p1_s1
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
        execution:
          onExecute:
            # Data from input resources is available as env variables in the step
            # Data from input resources is available as env variables in the step
            - echo $res_myFirstRepo_commitSha
            # The next two commands add variables to run state, which is available to all downstream steps in this run
            # Run state documentation: https://www.jfrog.com/confluence/display/JFROG/Creating+Stateful+Pipelines#CreatingStatefulPipelines-RunState
            - add_run_variables current_runid=$run_id
            - add_run_variables commitSha=$res_myFirstRepo_commitSha
            # This variable is written to pipeline state in p1_s3.
            # So this will be empty during first run and will be set to prior run number in subsequent runs
            # Pipeline state documentation: https://www.jfrog.com/confluence/display/JFROG/Creating+Stateful+Pipelines#CreatingStatefulPipelines-PipelineState
            - echo "Previous run ID is $prev_runid"
